# Generated by Django 6.0.3 on 2026-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_deal_created_by_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
