"""
This type stub file was generated by pyright.
"""

from rest_framework.settings import api_settings
from . import openapi
from .inspectors import DefaultSchema
from .openapi import AutoSchema, SchemaGenerator

"""
rest_framework.schemas

schemas:
    __init__.py
    generators.py   # Top-down schema generation
    inspectors.py   # Per-endpoint view introspection
    utils.py        # Shared helper functions
    views.py        # Houses `SchemaView`, `APIView` subclass.

We expose a minimal "public" API directly from `schemas`. This covers the
basic use-cases:

    from rest_framework.schemas import (
        AutoSchema,
        get_schema_view,
        SchemaGenerator,
    )

Other access should target the submodules directly
"""
def get_schema_view(title=..., url=..., description=..., urlconf=..., renderer_classes=..., public=..., patterns=..., generator_class=..., authentication_classes=..., permission_classes=..., version=...): # -> Callable[..., HttpResponse]:
    """
    Return a schema view.
    """
    ...

