"""
This type stub file was generated by pyright.
"""

def get_breadcrumbs(url, request=...):
    """
    Given a url returns a list of breadcrumbs, which are each a
    tuple of (name, url).
    """
    ...

