"""
This type stub file was generated by pyright.
"""

import json

"""
Helper classes for parsers.
"""
class JSONEncoder(json.JSONEncoder):
    """
    JSONEncoder subclass that knows how to encode date/time/timedelta,
    decimal types, generators and other basic python objects.
    """
    def default(self, obj): # -> str | float | tuple[Any, ...] | dict[Any, Any] | list[Any] | Any:
        ...
    


class CustomScalar:
    """
    CustomScalar that knows how to encode timedelta that renderer
    can understand.
    """
    @classmethod
    def represent_timedelta(cls, dumper, data):
        ...
    


