"""
This type stub file was generated by pyright.
"""

"""
Helper functions for creating user-friendly representations
of serializer classes and serializer fields.
"""
def manager_repr(value): # -> LiteralString | str:
    ...

def smart_repr(value): # -> LiteralString | str:
    ...

def field_repr(field, force_many=...): # -> str:
    ...

def serializer_repr(serializer, indent, force_many=...): # -> str:
    ...

def list_repr(serializer, indent): # -> str:
    ...

